version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # Puerto principal
      - "4571:4571" # Puerto debug opcional
    restart: always
    environment:
      - SERVICES=s3,sqs,sns,dynamodb,lambda,cloudwatch,iam,logs,events
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localstack
      - HOSTNAME_EXTERNAL=localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack:/var/lib/localstack

  terraform:
    image: hashicorp/terraform:1.9
    container_name: terraform_local
    working_dir: /workspace
    volumes:
      - ./terraform:/workspace
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
    depends_on:
      - localstack
    entrypoint: >
      sh -c "
        terraform init &&
        terraform apply -auto-approve -var-file=terraform.tfvars
      "
